var annotated_dup =
[
    [ "ax", null, [
      [ "NodeEditor", null, [
        [ "Detail", null, [
          [ "Animation", "da/d72/structax_1_1_node_editor_1_1_detail_1_1_animation.html", null ],
          [ "AnimationController", "dc/db8/structax_1_1_node_editor_1_1_detail_1_1_animation_controller.html", null ],
          [ "Config", "d8/ddf/structax_1_1_node_editor_1_1_detail_1_1_config.html", null ],
          [ "ContextMenuAction", "d8/d38/structax_1_1_node_editor_1_1_detail_1_1_context_menu_action.html", null ],
          [ "Control", "d5/d04/structax_1_1_node_editor_1_1_detail_1_1_control.html", null ],
          [ "CreateItemAction", "d8/d3f/structax_1_1_node_editor_1_1_detail_1_1_create_item_action.html", null ],
          [ "DeleteItemsAction", "d4/d6c/structax_1_1_node_editor_1_1_detail_1_1_delete_items_action.html", null ],
          [ "DragAction", "d4/de5/structax_1_1_node_editor_1_1_detail_1_1_drag_action.html", null ],
          [ "EditorAction", "d2/d5f/structax_1_1_node_editor_1_1_detail_1_1_editor_action.html", null ],
          [ "EditorContext", "d0/d01/structax_1_1_node_editor_1_1_detail_1_1_editor_context.html", "d0/d01/structax_1_1_node_editor_1_1_detail_1_1_editor_context" ],
          [ "FlowAnimation", "d5/dda/structax_1_1_node_editor_1_1_detail_1_1_flow_animation.html", null ],
          [ "FlowAnimationController", "d7/d49/structax_1_1_node_editor_1_1_detail_1_1_flow_animation_controller.html", null ],
          [ "FringeScaleRef", "d4/dc4/structax_1_1_node_editor_1_1_detail_1_1_fringe_scale_ref.html", null ],
          [ "FringeScaleScope", "d2/d49/structax_1_1_node_editor_1_1_detail_1_1_fringe_scale_scope.html", null ],
          [ "HintBuilder", "d9/d24/structax_1_1_node_editor_1_1_detail_1_1_hint_builder.html", null ],
          [ "Link", "d9/d26/structax_1_1_node_editor_1_1_detail_1_1_link.html", null ],
          [ "NavigateAction", "d1/d2e/structax_1_1_node_editor_1_1_detail_1_1_navigate_action.html", null ],
          [ "NavigateAnimation", "da/d4a/structax_1_1_node_editor_1_1_detail_1_1_navigate_animation.html", null ],
          [ "Node", "d9/dae/structax_1_1_node_editor_1_1_detail_1_1_node.html", null ],
          [ "NodeBuilder", "de/d92/structax_1_1_node_editor_1_1_detail_1_1_node_builder.html", null ],
          [ "NodeSettings", "d1/d51/structax_1_1_node_editor_1_1_detail_1_1_node_settings.html", null ],
          [ "Object", "d3/db1/structax_1_1_node_editor_1_1_detail_1_1_object.html", null ],
          [ "ObjectId", "d2/dd0/structax_1_1_node_editor_1_1_detail_1_1_object_id.html", null ],
          [ "ObjectWrapper", "df/d9e/structax_1_1_node_editor_1_1_detail_1_1_object_wrapper.html", null ],
          [ "Pin", "df/d26/structax_1_1_node_editor_1_1_detail_1_1_pin.html", null ],
          [ "SelectAction", "d7/d4f/structax_1_1_node_editor_1_1_detail_1_1_select_action.html", null ],
          [ "Settings", "d7/d91/structax_1_1_node_editor_1_1_detail_1_1_settings.html", null ],
          [ "ShortcutAction", "da/d1d/structax_1_1_node_editor_1_1_detail_1_1_shortcut_action.html", null ],
          [ "SizeAction", "d1/d47/structax_1_1_node_editor_1_1_detail_1_1_size_action.html", null ],
          [ "Style", "d8/db8/structax_1_1_node_editor_1_1_detail_1_1_style.html", null ]
        ] ],
        [ "Details", null, [
          [ "SafePointerType", "de/de3/structax_1_1_node_editor_1_1_details_1_1_safe_pointer_type.html", null ],
          [ "SafeType", "d9/dc0/structax_1_1_node_editor_1_1_details_1_1_safe_type.html", null ]
        ] ],
        [ "Config", "dd/d5d/structax_1_1_node_editor_1_1_config.html", null ],
        [ "LinkId", "df/d10/structax_1_1_node_editor_1_1_link_id.html", null ],
        [ "NodeId", "d0/d73/structax_1_1_node_editor_1_1_node_id.html", null ],
        [ "PinId", "da/d9a/structax_1_1_node_editor_1_1_pin_id.html", null ],
        [ "Style", "d8/d40/structax_1_1_node_editor_1_1_style.html", null ]
      ] ]
    ] ],
    [ "config", null, [
      [ "Config", "d7/dcc/classconfig_1_1_config.html", null ],
      [ "ConfigSection", "d5/d37/classconfig_1_1_config_section.html", "d5/d37/classconfig_1_1_config_section" ],
      [ "ConfigStrings", "d7/d47/classconfig_1_1_config_strings.html", "d7/d47/classconfig_1_1_config_strings" ],
      [ "Variant64", "da/d04/classconfig_1_1_variant64.html", null ]
    ] ],
    [ "crude_json", null, [
      [ "value", "d6/de8/structcrude__json_1_1value.html", "d6/de8/structcrude__json_1_1value" ]
    ] ],
    [ "D3D12MA", null, [
      [ "Allocation", "da/db3/class_d3_d12_m_a_1_1_allocation.html", "da/db3/class_d3_d12_m_a_1_1_allocation" ],
      [ "ALLOCATION_CALLBACKS", "d0/dea/struct_d3_d12_m_a_1_1_a_l_l_o_c_a_t_i_o_n___c_a_l_l_b_a_c_k_s.html", "d0/dea/struct_d3_d12_m_a_1_1_a_l_l_o_c_a_t_i_o_n___c_a_l_l_b_a_c_k_s" ],
      [ "ALLOCATION_DESC", "da/d97/struct_d3_d12_m_a_1_1_a_l_l_o_c_a_t_i_o_n___d_e_s_c.html", "da/d97/struct_d3_d12_m_a_1_1_a_l_l_o_c_a_t_i_o_n___d_e_s_c" ],
      [ "AllocationObjectAllocator", "d0/d7d/class_d3_d12_m_a_1_1_allocation_object_allocator.html", null ],
      [ "AllocationRequest", "dd/d8d/struct_d3_d12_m_a_1_1_allocation_request.html", null ],
      [ "Allocator", "dd/d32/class_d3_d12_m_a_1_1_allocator.html", "dd/d32/class_d3_d12_m_a_1_1_allocator" ],
      [ "ALLOCATOR_DESC", "d0/de8/struct_d3_d12_m_a_1_1_a_l_l_o_c_a_t_o_r___d_e_s_c.html", "d0/de8/struct_d3_d12_m_a_1_1_a_l_l_o_c_a_t_o_r___d_e_s_c" ],
      [ "AllocatorPimpl", "d8/dfe/class_d3_d12_m_a_1_1_allocator_pimpl.html", null ],
      [ "BlockMetadata", "d6/d68/class_d3_d12_m_a_1_1_block_metadata.html", null ],
      [ "BlockMetadata_Linear", "d8/d87/class_d3_d12_m_a_1_1_block_metadata___linear.html", null ],
      [ "BlockMetadata_TLSF", "d7/d25/class_d3_d12_m_a_1_1_block_metadata___t_l_s_f.html", null ],
      [ "BlockVector", "d0/d6f/class_d3_d12_m_a_1_1_block_vector.html", null ],
      [ "Budget", "d7/dff/struct_d3_d12_m_a_1_1_budget.html", "d7/dff/struct_d3_d12_m_a_1_1_budget" ],
      [ "CommittedAllocationList", "d3/d4b/class_d3_d12_m_a_1_1_committed_allocation_list.html", null ],
      [ "CommittedAllocationListItemTraits", "dd/d17/struct_d3_d12_m_a_1_1_committed_allocation_list_item_traits.html", null ],
      [ "CommittedAllocationParameters", "d8/d84/struct_d3_d12_m_a_1_1_committed_allocation_parameters.html", null ],
      [ "CREATE_RESOURCE_PARAMS", "d3/d76/struct_d3_d12_m_a_1_1_c_r_e_a_t_e___r_e_s_o_u_r_c_e___p_a_r_a_m_s.html", null ],
      [ "CurrentBudgetData", "d9/dec/class_d3_d12_m_a_1_1_current_budget_data.html", null ],
      [ "DEFRAGMENTATION_DESC", "d8/dbc/struct_d3_d12_m_a_1_1_d_e_f_r_a_g_m_e_n_t_a_t_i_o_n___d_e_s_c.html", "d8/dbc/struct_d3_d12_m_a_1_1_d_e_f_r_a_g_m_e_n_t_a_t_i_o_n___d_e_s_c" ],
      [ "DEFRAGMENTATION_MOVE", "d3/def/struct_d3_d12_m_a_1_1_d_e_f_r_a_g_m_e_n_t_a_t_i_o_n___m_o_v_e.html", "d3/def/struct_d3_d12_m_a_1_1_d_e_f_r_a_g_m_e_n_t_a_t_i_o_n___m_o_v_e" ],
      [ "DEFRAGMENTATION_PASS_MOVE_INFO", "d6/dda/struct_d3_d12_m_a_1_1_d_e_f_r_a_g_m_e_n_t_a_t_i_o_n___p_a_s_s___m_o_v_e___i_n_f_o.html", "d6/dda/struct_d3_d12_m_a_1_1_d_e_f_r_a_g_m_e_n_t_a_t_i_o_n___p_a_s_s___m_o_v_e___i_n_f_o" ],
      [ "DEFRAGMENTATION_STATS", "d7/d2c/struct_d3_d12_m_a_1_1_d_e_f_r_a_g_m_e_n_t_a_t_i_o_n___s_t_a_t_s.html", "d7/d2c/struct_d3_d12_m_a_1_1_d_e_f_r_a_g_m_e_n_t_a_t_i_o_n___s_t_a_t_s" ],
      [ "DefragmentationContext", "d0/d68/class_d3_d12_m_a_1_1_defragmentation_context.html", "d0/d68/class_d3_d12_m_a_1_1_defragmentation_context" ],
      [ "DefragmentationContextPimpl", "df/d3c/class_d3_d12_m_a_1_1_defragmentation_context_pimpl.html", null ],
      [ "DetailedStatistics", "df/d95/struct_d3_d12_m_a_1_1_detailed_statistics.html", "df/d95/struct_d3_d12_m_a_1_1_detailed_statistics" ],
      [ "IntrusiveLinkedList", "d7/d8d/class_d3_d12_m_a_1_1_intrusive_linked_list.html", null ],
      [ "JsonWriter", "d4/d71/class_d3_d12_m_a_1_1_json_writer.html", null ],
      [ "List", "db/d01/class_d3_d12_m_a_1_1_list.html", "db/d01/class_d3_d12_m_a_1_1_list" ],
      [ "MemoryBlock", "d9/d1a/class_d3_d12_m_a_1_1_memory_block.html", null ],
      [ "Mutex", "d6/d79/class_d3_d12_m_a_1_1_mutex.html", null ],
      [ "MutexLock", "d2/d9c/struct_d3_d12_m_a_1_1_mutex_lock.html", null ],
      [ "MutexLockRead", "dd/d83/struct_d3_d12_m_a_1_1_mutex_lock_read.html", null ],
      [ "MutexLockWrite", "da/d33/struct_d3_d12_m_a_1_1_mutex_lock_write.html", null ],
      [ "NormalBlock", "d0/da2/class_d3_d12_m_a_1_1_normal_block.html", null ],
      [ "Pool", "d5/d18/class_d3_d12_m_a_1_1_pool.html", "d5/d18/class_d3_d12_m_a_1_1_pool" ],
      [ "POOL_DESC", "dd/df1/struct_d3_d12_m_a_1_1_p_o_o_l___d_e_s_c.html", "dd/df1/struct_d3_d12_m_a_1_1_p_o_o_l___d_e_s_c" ],
      [ "PoolAllocator", "d3/d95/class_d3_d12_m_a_1_1_pool_allocator.html", null ],
      [ "PoolListItemTraits", "d3/d55/struct_d3_d12_m_a_1_1_pool_list_item_traits.html", null ],
      [ "PoolPimpl", "db/d23/class_d3_d12_m_a_1_1_pool_pimpl.html", null ],
      [ "RWMutex", "d6/d36/class_d3_d12_m_a_1_1_r_w_mutex.html", null ],
      [ "Statistics", "d1/d92/struct_d3_d12_m_a_1_1_statistics.html", "d1/d92/struct_d3_d12_m_a_1_1_statistics" ],
      [ "StringBuilder", "d6/d9d/class_d3_d12_m_a_1_1_string_builder.html", null ],
      [ "Suballocation", "da/dea/struct_d3_d12_m_a_1_1_suballocation.html", null ],
      [ "SuballocationItemSizeLess", "d6/d69/struct_d3_d12_m_a_1_1_suballocation_item_size_less.html", null ],
      [ "SuballocationOffsetGreater", "db/d03/struct_d3_d12_m_a_1_1_suballocation_offset_greater.html", null ],
      [ "SuballocationOffsetLess", "d5/def/struct_d3_d12_m_a_1_1_suballocation_offset_less.html", null ],
      [ "TotalStatistics", "d5/d33/struct_d3_d12_m_a_1_1_total_statistics.html", "d5/d33/struct_d3_d12_m_a_1_1_total_statistics" ],
      [ "Vector", "dc/d6a/class_d3_d12_m_a_1_1_vector.html", null ],
      [ "VIRTUAL_ALLOCATION_DESC", "db/da5/struct_d3_d12_m_a_1_1_v_i_r_t_u_a_l___a_l_l_o_c_a_t_i_o_n___d_e_s_c.html", "db/da5/struct_d3_d12_m_a_1_1_v_i_r_t_u_a_l___a_l_l_o_c_a_t_i_o_n___d_e_s_c" ],
      [ "VIRTUAL_ALLOCATION_INFO", "d6/db5/struct_d3_d12_m_a_1_1_v_i_r_t_u_a_l___a_l_l_o_c_a_t_i_o_n___i_n_f_o.html", "d6/db5/struct_d3_d12_m_a_1_1_v_i_r_t_u_a_l___a_l_l_o_c_a_t_i_o_n___i_n_f_o" ],
      [ "VIRTUAL_BLOCK_DESC", "df/da5/struct_d3_d12_m_a_1_1_v_i_r_t_u_a_l___b_l_o_c_k___d_e_s_c.html", "df/da5/struct_d3_d12_m_a_1_1_v_i_r_t_u_a_l___b_l_o_c_k___d_e_s_c" ],
      [ "VirtualAllocation", "d2/d0d/struct_d3_d12_m_a_1_1_virtual_allocation.html", "d2/d0d/struct_d3_d12_m_a_1_1_virtual_allocation" ],
      [ "VirtualBlock", "de/d96/class_d3_d12_m_a_1_1_virtual_block.html", "de/d96/class_d3_d12_m_a_1_1_virtual_block" ],
      [ "VirtualBlockPimpl", "db/dad/class_d3_d12_m_a_1_1_virtual_block_pimpl.html", null ],
      [ "ZeroInitializedRange", "d6/d53/class_d3_d12_m_a_1_1_zero_initialized_range.html", null ]
    ] ],
    [ "game", null, [
      [ "CharacterComponent", "dd/d07/classgame_1_1_character_component.html", null ],
      [ "CharacterSystem", "da/dd9/classgame_1_1_character_system.html", null ],
      [ "GameState", "d2/dd8/classgame_1_1_game_state.html", null ],
      [ "PlayerComponent", "df/d76/classgame_1_1_player_component.html", null ],
      [ "PlayerSystem", "d7/d0c/classgame_1_1_player_system.html", null ]
    ] ],
    [ "GraphEditor", null, [
      [ "Delegate", "d2/d1a/struct_graph_editor_1_1_delegate.html", null ],
      [ "Link", "d9/d83/struct_graph_editor_1_1_link.html", null ],
      [ "Node", "d4/dad/struct_graph_editor_1_1_node.html", null ],
      [ "Options", "de/d28/struct_graph_editor_1_1_options.html", null ],
      [ "Template", "d0/d53/struct_graph_editor_1_1_template.html", null ],
      [ "ViewState", "dc/d22/struct_graph_editor_1_1_view_state.html", null ]
    ] ],
    [ "hgfx", null, [
      [ "DX12ShaderCompiler", "d7/d19/classhgfx_1_1_d_x12_shader_compiler.html", null ]
    ] ],
    [ "hq", null, [
      [ "ConfigSystem", "df/d1f/classhq_1_1_config_system.html", null ],
      [ "DefaultAllocator", "d4/dc9/classhq_1_1_default_allocator.html", null ],
      [ "EngineContext", "db/db0/classhq_1_1_engine_context.html", null ],
      [ "EngineTimer", "d2/d39/classhq_1_1_engine_timer.html", "d2/d39/classhq_1_1_engine_timer" ],
      [ "FDX12ConstantBuffer", "d3/d8b/classhq_1_1_f_d_x12_constant_buffer.html", null ],
      [ "FDX12DepthBuffer", "db/d71/classhq_1_1_f_d_x12_depth_buffer.html", null ],
      [ "FDX12DescriptorHeap", "df/ddc/classhq_1_1_f_d_x12_descriptor_heap.html", null ],
      [ "FDX12Light", "dd/d75/structhq_1_1_f_d_x12_light.html", null ],
      [ "FDX12LightProxy", "df/d94/structhq_1_1_f_d_x12_light_proxy.html", null ],
      [ "FDX12Material", "d4/d1d/structhq_1_1_f_d_x12_material.html", null ],
      [ "FDX12MeshData", "dd/df3/structhq_1_1_f_d_x12_mesh_data.html", null ],
      [ "FDX12PixelBuffer", "d5/de8/classhq_1_1_f_d_x12_pixel_buffer.html", null ],
      [ "FDX12Renderer", "db/d2f/classhq_1_1_f_d_x12_renderer.html", null ],
      [ "FDX12RenderProxy", "dd/db2/structhq_1_1_f_d_x12_render_proxy.html", null ],
      [ "FDX12StructBuffer", "d6/d51/classhq_1_1_f_d_x12_struct_buffer.html", null ],
      [ "FFreeList", "db/de4/structhq_1_1_f_free_list.html", null ],
      [ "FileWatcher", "dd/d75/classhq_1_1_file_watcher.html", null ],
      [ "FileWatcherImpl", "df/dc6/classhq_1_1_file_watcher_impl.html", null ],
      [ "FLight", "d6/dce/structhq_1_1_f_light.html", null ],
      [ "FRenderMaterialParams", "d9/d27/structhq_1_1_f_render_material_params.html", null ],
      [ "FRenderMesh", "d2/d35/structhq_1_1_f_render_mesh.html", null ],
      [ "FTexture2DParams", "db/d49/structhq_1_1_f_texture2_d_params.html", null ],
      [ "FVertexLayout", "dc/d55/structhq_1_1_f_vertex_layout.html", null ],
      [ "FVertexLayoutQuad", "dc/d61/structhq_1_1_f_vertex_layout_quad.html", null ],
      [ "HokkuEngine", "de/dd2/classhq_1_1_hokku_engine.html", null ],
      [ "IEngineModule", "d4/de6/classhq_1_1_i_engine_module.html", null ],
      [ "IFileObserver", "da/d7c/classhq_1_1_i_file_observer.html", null ],
      [ "InputSystem", "dd/dc4/classhq_1_1_input_system.html", "dd/dc4/classhq_1_1_input_system" ],
      [ "InputSystemImpl", "d9/d93/structhq_1_1_input_system_impl.html", null ],
      [ "Light", "d8/d94/structhq_1_1_light.html", null ],
      [ "LogCallback", "d3/df9/structhq_1_1_log_callback.html", null ],
      [ "LogConsumer", "d8/d61/classhq_1_1_log_consumer.html", null ],
      [ "LogData", "d3/da3/structhq_1_1_log_data.html", null ],
      [ "LogEvent", "d1/d21/structhq_1_1_log_event.html", null ],
      [ "ObjConstants", "dc/d56/structhq_1_1_obj_constants.html", null ],
      [ "ObserverHandle", "dc/d9a/structhq_1_1_observer_handle.html", null ],
      [ "PassConstants", "d1/d63/structhq_1_1_pass_constants.html", null ],
      [ "SEngineState", "d1/d98/structhq_1_1_s_engine_state.html", null ],
      [ "SInputSub", "d9/d61/structhq_1_1_s_input_sub.html", null ],
      [ "SInputSubComparer", "d3/d31/structhq_1_1_s_input_sub_comparer.html", null ],
      [ "SInputSubHasher", "d6/daf/structhq_1_1_s_input_sub_hasher.html", null ],
      [ "SRenderParameters", "db/d41/structhq_1_1_s_render_parameters.html", null ],
      [ "SScreenParameters", "df/daf/structhq_1_1_s_screen_parameters.html", null ],
      [ "SVMem", "d7/d10/structhq_1_1_s_v_mem.html", null ],
      [ "SystemAllocator", "d3/d1f/classhq_1_1_system_allocator.html", null ],
      [ "TAllocatorAccessor", "d8/d18/structhq_1_1_t_allocator_accessor.html", null ],
      [ "TAllocatorAccessor< TAlloc >", "d2/dbb/structhq_1_1_t_allocator_accessor_3_01_t_alloc_01_4.html", null ],
      [ "TAllocatorTraits", "d6/df5/structhq_1_1_t_allocator_traits.html", null ],
      [ "TAllocatorTraits< DefaultAllocator >", "df/d0b/structhq_1_1_t_allocator_traits_3_01_default_allocator_01_4.html", null ],
      [ "TDefaultComparer", "da/dbc/structhq_1_1_t_default_comparer.html", null ],
      [ "TDefaultComparer< f32 >", "d5/d4d/structhq_1_1_t_default_comparer_3_01f32_01_4.html", null ],
      [ "TDefaultComparer< f64 >", "d5/d8a/structhq_1_1_t_default_comparer_3_01f64_01_4.html", null ],
      [ "TDefaultHasher", "d0/de1/structhq_1_1_t_default_hasher.html", null ],
      [ "TDefaultHasher< FName >", "d0/d36/structhq_1_1_t_default_hasher_3_01_f_name_01_4.html", null ],
      [ "TDefaultHasher< std::string >", "d0/de0/structhq_1_1_t_default_hasher_3_01std_1_1string_01_4.html", null ],
      [ "TDefaultHasher< std::string_view >", "d1/def/structhq_1_1_t_default_hasher_3_01std_1_1string__view_01_4.html", null ],
      [ "TDispatcher", "df/d29/classhq_1_1_t_dispatcher.html", "df/d29/classhq_1_1_t_dispatcher" ],
      [ "THeterogenousLookupType", "d4/d30/structhq_1_1_t_heterogenous_lookup_type.html", null ],
      [ "THeterogenousLookupType< hqmeta::MetaClass >", "dc/df7/structhq_1_1_t_heterogenous_lookup_type_3_01hqmeta_1_1_meta_class_01_4.html", null ],
      [ "THeterogenousLookupType< hqmeta::MetaEnum >", "d1/dac/structhq_1_1_t_heterogenous_lookup_type_3_01hqmeta_1_1_meta_enum_01_4.html", null ],
      [ "THeterogenousLookupType< hqmeta::MetaType >", "df/d5f/structhq_1_1_t_heterogenous_lookup_type_3_01hqmeta_1_1_meta_type_01_4.html", null ],
      [ "THeterogenousLookupType< Path >", "d4/d9d/structhq_1_1_t_heterogenous_lookup_type_3_01_path_01_4.html", null ],
      [ "THeterogenousLookupType< std::string >", "de/d74/structhq_1_1_t_heterogenous_lookup_type_3_01std_1_1string_01_4.html", null ],
      [ "THeterogenousLookupType< world::SceneUpdateReg >", "d4/df3/structhq_1_1_t_heterogenous_lookup_type_3_01world_1_1_scene_update_reg_01_4.html", null ],
      [ "TModuleContext", "dd/d4f/classhq_1_1_t_module_context.html", null ],
      [ "TObserver", "d4/d3e/classhq_1_1_t_observer.html", null ],
      [ "TRenderEntities", "df/d81/classhq_1_1_t_render_entities.html", "df/d81/classhq_1_1_t_render_entities" ],
      [ "TVirtualStackAllocator", "d6/d72/classhq_1_1_t_virtual_stack_allocator.html", null ],
      [ "UploadBuffer", "d9/d42/classhq_1_1_upload_buffer.html", null ]
    ] ],
    [ "hqed", null, [
      [ "Context_EntityEditor", "df/df5/structhqed_1_1_context___entity_editor.html", null ],
      [ "EditorLayout", "d7/d57/classhqed_1_1_editor_layout.html", null ],
      [ "HokkuEditor", "d3/d9f/classhqed_1_1_hokku_editor.html", null ],
      [ "IEditorWidget", "d8/dfe/classhqed_1_1_i_editor_widget.html", null ],
      [ "Widget_AssetBrowser", "d7/d37/classhqed_1_1_widget___asset_browser.html", null ],
      [ "Widget_ComponentPopup", "dc/de3/structhqed_1_1_widget___component_popup.html", null ],
      [ "Widget_EntityEditor", "d6/d45/classhqed_1_1_widget___entity_editor.html", null ]
    ] ],
    [ "hqfs", null, [
      [ "DirectoryEnumerator", "de/d98/classhqfs_1_1_directory_enumerator.html", "de/d98/classhqfs_1_1_directory_enumerator" ],
      [ "DirectoryIterator", "d0/d5b/classhqfs_1_1_directory_iterator.html", "d0/d5b/classhqfs_1_1_directory_iterator" ],
      [ "File", "de/dd0/classhqfs_1_1_file.html", "de/dd0/classhqfs_1_1_file" ],
      [ "HFile", "db/d93/structhqfs_1_1_h_file.html", null ],
      [ "SFileAttr", "dd/d12/structhqfs_1_1_s_file_attr.html", null ]
    ] ],
    [ "hqgltf", null, [
      [ "GLTFExtracted", "d9/dde/structhqgltf_1_1_g_l_t_f_extracted.html", null ],
      [ "GLTFFormat", "d6/d5d/structhqgltf_1_1_g_l_t_f_format.html", null ],
      [ "GLTFRoot", "d9/da2/structhqgltf_1_1_g_l_t_f_root.html", "d9/da2/structhqgltf_1_1_g_l_t_f_root" ]
    ] ],
    [ "hqmeta", null, [
      [ "ENotImplementedT", "d0/d09/structhqmeta_1_1_e_not_implemented_t.html", null ],
      [ "InputBinaryArchive", "dc/d82/classhqmeta_1_1_input_binary_archive.html", null ],
      [ "InputJSONArchive", "db/db0/classhqmeta_1_1_input_j_s_o_n_archive.html", null ],
      [ "InputJSONArchiveImpl", "d8/df6/classhqmeta_1_1_input_j_s_o_n_archive_impl.html", null ],
      [ "MetaCallable", "de/d18/classhqmeta_1_1_meta_callable.html", null ],
      [ "MetaClass", "d6/d37/classhqmeta_1_1_meta_class.html", null ],
      [ "MetaDiff", "d4/ddd/classhqmeta_1_1_meta_diff.html", null ],
      [ "MetaEnum", "d7/de4/classhqmeta_1_1_meta_enum.html", null ],
      [ "MetaEnumConstant", "d7/d4e/structhqmeta_1_1_meta_enum_constant.html", null ],
      [ "MetaField", "d8/d09/classhqmeta_1_1_meta_field.html", null ],
      [ "MetaRegistry", "d5/d63/classhqmeta_1_1_meta_registry.html", null ],
      [ "MetaType", "d0/d3d/classhqmeta_1_1_meta_type.html", null ],
      [ "NotImplementedT", "da/dc9/structhqmeta_1_1_not_implemented_t.html", null ],
      [ "OutputBinaryArchive", "df/d10/classhqmeta_1_1_output_binary_archive.html", null ],
      [ "OutputJSONArchive", "d5/d05/classhqmeta_1_1_output_j_s_o_n_archive.html", null ],
      [ "OutputJSONArchiveImpl", "dc/dea/classhqmeta_1_1_output_j_s_o_n_archive_impl.html", null ],
      [ "VTable", "de/dd7/structhqmeta_1_1_v_table.html", null ]
    ] ],
    [ "hqrs", null, [
      [ "HResource", "df/d72/structhqrs_1_1_h_resource.html", null ],
      [ "IResourceData", "df/d69/structhqrs_1_1_i_resource_data.html", "df/d69/structhqrs_1_1_i_resource_data" ],
      [ "IResourceLoader", "db/d63/structhqrs_1_1_i_resource_loader.html", "db/d63/structhqrs_1_1_i_resource_loader" ],
      [ "IResourceObserver", "d5/df6/classhqrs_1_1_i_resource_observer.html", null ],
      [ "Resource", "d8/dc8/classhqrs_1_1_resource.html", "d8/dc8/classhqrs_1_1_resource" ],
      [ "ResourceCompilationContext", "d9/d93/classhqrs_1_1_resource_compilation_context.html", null ],
      [ "ResourceIndexer", "d8/da9/classhqrs_1_1_resource_indexer.html", null ],
      [ "ResourceManager", "dc/d59/classhqrs_1_1_resource_manager.html", null ],
      [ "ResourceNotifier", "d0/db5/classhqrs_1_1_resource_notifier.html", null ],
      [ "ResourceToken", "d4/d01/structhqrs_1_1_resource_token.html", null ],
      [ "SMTResource", "d2/d15/structhqrs_1_1_s_m_t_resource.html", null ],
      [ "SResource", "d2/d2f/structhqrs_1_1_s_resource.html", null ],
      [ "SResourceAwaitable", "d2/d8f/structhqrs_1_1_s_resource_awaitable.html", null ],
      [ "SResourceEntry", "de/d58/structhqrs_1_1_s_resource_entry.html", null ],
      [ "SResourceIndex", "d6/d94/structhqrs_1_1_s_resource_index.html", null ],
      [ "SResourceLoader", "dc/d90/structhqrs_1_1_s_resource_loader.html", null ],
      [ "SResourceRequest", "d4/d81/classhqrs_1_1_s_resource_request.html", null ],
      [ "TResourceData", "d4/d73/structhqrs_1_1_t_resource_data.html", null ]
    ] ],
    [ "hsfx", null, [
      [ "AudioEngine", "dc/d9f/classhsfx_1_1_audio_engine.html", "dc/d9f/classhsfx_1_1_audio_engine" ],
      [ "AudioEngineImpl", "dc/d6b/classhsfx_1_1_audio_engine_impl.html", null ],
      [ "AudioLoader", "de/d8b/classhsfx_1_1_audio_loader.html", "de/d8b/classhsfx_1_1_audio_loader" ],
      [ "AudioResource", "d1/da7/classhsfx_1_1_audio_resource.html", null ]
    ] ],
    [ "ht", null, [
      [ "StackSlot", "d6/ddb/structht_1_1_stack_slot.html", null ],
      [ "TMPMCQueue", "de/d59/classht_1_1_t_m_p_m_c_queue.html", null ],
      [ "TMPMCStack", "d8/daa/classht_1_1_t_m_p_m_c_stack.html", null ],
      [ "TQueueSlot", "da/d4c/structht_1_1_t_queue_slot.html", null ]
    ] ],
    [ "ImCanvasDetails", null, [
      [ "FringeScaleRef", "d2/d1f/struct_im_canvas_details_1_1_fringe_scale_ref.html", null ],
      [ "VtxCurrentOffsetRef", "d7/dfe/struct_im_canvas_details_1_1_vtx_current_offset_ref.html", null ]
    ] ],
    [ "ImCurveEdit", null, [
      [ "Delegate", "dc/d3f/struct_im_curve_edit_1_1_delegate.html", null ],
      [ "EditPoint", "de/d61/struct_im_curve_edit_1_1_edit_point.html", null ]
    ] ],
    [ "ImGradient", null, [
      [ "Delegate", "d4/dff/struct_im_gradient_1_1_delegate.html", null ]
    ] ],
    [ "ImGuiEx", null, [
      [ "Canvas", "de/d4a/struct_im_gui_ex_1_1_canvas.html", null ],
      [ "CanvasView", "de/d73/struct_im_gui_ex_1_1_canvas_view.html", null ]
    ] ],
    [ "IMGUIZMO_NAMESPACE", null, [
      [ "Context", "d8/dc1/struct_i_m_g_u_i_z_m_o___n_a_m_e_s_p_a_c_e_1_1_context.html", null ],
      [ "matrix_t", "dc/d95/struct_i_m_g_u_i_z_m_o___n_a_m_e_s_p_a_c_e_1_1matrix__t.html", null ],
      [ "Style", "d1/dbf/struct_i_m_g_u_i_z_m_o___n_a_m_e_s_p_a_c_e_1_1_style.html", null ],
      [ "vec_t", "d9/de9/struct_i_m_g_u_i_z_m_o___n_a_m_e_s_p_a_c_e_1_1vec__t.html", null ]
    ] ],
    [ "ImSequencer", null, [
      [ "SequenceInterface", "dc/d91/struct_im_sequencer_1_1_sequence_interface.html", null ]
    ] ],
    [ "math", null, [
      [ "FEuler", "d9/da1/structmath_1_1_f_euler.html", null ],
      [ "FMatrix4x4", "d3/d7e/structmath_1_1_f_matrix4x4.html", null ],
      [ "FTransform", "d9/d5c/structmath_1_1_f_transform.html", null ],
      [ "FVector2", "d1/d6d/structmath_1_1_f_vector2.html", null ],
      [ "FVector3", "df/dda/structmath_1_1_f_vector3.html", null ],
      [ "FVector4", "de/d4a/structmath_1_1_f_vector4.html", null ],
      [ "FVectorHasher", "db/d25/structmath_1_1_f_vector_hasher.html", null ],
      [ "FVersor", "de/d64/structmath_1_1_f_versor.html", null ]
    ] ],
    [ "persistence", null, [
      [ "SaveManager", "d9/d44/classpersistence_1_1_save_manager.html", null ],
      [ "SaveSlot", "df/d7f/classpersistence_1_1_save_slot.html", null ],
      [ "SaveSystem", "d1/dfa/classpersistence_1_1_save_system.html", null ]
    ] ],
    [ "physics", null, [
      [ "SPhysicsMaterial", "db/db4/structphysics_1_1_s_physics_material.html", null ],
      [ "TraceResult", "d3/d75/structphysics_1_1_trace_result.html", null ]
    ] ],
    [ "rpg", null, [
      [ "JournalSystem", "d4/d8a/classrpg_1_1_journal_system.html", null ]
    ] ],
    [ "std", null, [
      [ "hash< CXCursor >", "dd/d0b/structstd_1_1hash_3_01_c_x_cursor_01_4.html", null ]
    ] ],
    [ "stdext", null, [
      [ "inplace_function_detail", null, [
        [ "aligned_storage", "db/dc4/structstdext_1_1inplace__function__detail_1_1aligned__storage.html", null ],
        [ "aligned_storage_helper", "d2/d24/unionstdext_1_1inplace__function__detail_1_1aligned__storage__helper.html", "d2/d24/unionstdext_1_1inplace__function__detail_1_1aligned__storage__helper" ],
        [ "is_inplace_function", "d4/d57/structstdext_1_1inplace__function__detail_1_1is__inplace__function.html", null ],
        [ "is_inplace_function< inplace_function< Sig, Cap, Align > >", "d0/d2a/structstdext_1_1inplace__function__detail_1_1is__inplace__function_3_01inplace__function_3_01_si41ee2a638dd5f73150c3f7ba36ea58fb.html", null ],
        [ "is_invocable_r_impl", "d1/d71/structstdext_1_1inplace__function__detail_1_1is__invocable__r__impl.html", null ],
        [ "is_invocable_r_impl< decltype(accept< R >(std::declval< F >()(std::declval< Args >()...))), R, F, Args... >", "d5/d43/structstdext_1_1inplace__function__detail_1_1is__invocable__r__impl_3_01decltype_07accept_3_01_r6f412320b5df6abaab245a8953795def.html", null ],
        [ "is_invocable_r_impl< decltype(std::declval< F >()(std::declval< Args >()...), void()), const void, F, Args... >", "d6/df6/structstdext_1_1inplace__function__detail_1_1is__invocable__r__impl_3_01decltype_07std_1_1declva0703f1e83dddb8a20266c4ffd32a0252.html", null ],
        [ "is_invocable_r_impl< decltype(std::declval< F >()(std::declval< Args >()...), void()), void, F, Args... >", "dc/d1c/structstdext_1_1inplace__function__detail_1_1is__invocable__r__impl_3_01decltype_07std_1_1declva006ee830f256b5a8679d85e3bd24c12b.html", null ],
        [ "is_valid_inplace_dst", "d1/d1b/structstdext_1_1inplace__function__detail_1_1is__valid__inplace__dst.html", null ],
        [ "vtable", "de/d53/structstdext_1_1inplace__function__detail_1_1vtable.html", null ],
        [ "wrapper", "d6/d1b/structstdext_1_1inplace__function__detail_1_1wrapper.html", null ]
      ] ],
      [ "inplace_function", "d4/d42/classstdext_1_1inplace__function.html", null ],
      [ "inplace_function< R(Args...), Capacity, Alignment >", "d7/d1c/classstdext_1_1inplace__function_3_01_r_07_args_8_8_8_08_00_01_capacity_00_01_alignment_01_4.html", null ]
    ] ],
    [ "world", null, [
      [ "AttachBoxRequest", "da/d70/structworld_1_1_attach_box_request.html", null ],
      [ "AttachMeshRequest", "da/d6f/structworld_1_1_attach_mesh_request.html", null ],
      [ "AttachRenderableRequest", "d8/d2c/structworld_1_1_attach_renderable_request.html", null ],
      [ "AttachSphereRequest", "da/d20/structworld_1_1_attach_sphere_request.html", null ],
      [ "AudioComponent", "d3/d41/structworld_1_1_audio_component.html", null ],
      [ "AudioSystem", "d8/d08/classworld_1_1_audio_system.html", "d8/d08/classworld_1_1_audio_system" ],
      [ "CameraComponent", "db/d4e/structworld_1_1_camera_component.html", null ],
      [ "CameraSystem", "d1/dfd/classworld_1_1_camera_system.html", null ],
      [ "ComponentStub", "d3/df5/structworld_1_1_component_stub.html", null ],
      [ "DetachRenderableRequest", "dd/d5e/structworld_1_1_detach_renderable_request.html", null ],
      [ "EntityStub", "db/d6c/classworld_1_1_entity_stub.html", null ],
      [ "FragmentStub", "d0/de8/structworld_1_1_fragment_stub.html", null ],
      [ "GizmoSystem", "d6/d75/classworld_1_1_gizmo_system.html", "d6/d75/classworld_1_1_gizmo_system" ],
      [ "GLTFInstance", "d4/d13/structworld_1_1_g_l_t_f_instance.html", null ],
      [ "GLTFLoader", "d3/de6/classworld_1_1_g_l_t_f_loader.html", "d3/de6/classworld_1_1_g_l_t_f_loader" ],
      [ "GLTFMaterial", "d7/df6/structworld_1_1_g_l_t_f_material.html", null ],
      [ "GLTFMesh", "dd/d55/structworld_1_1_g_l_t_f_mesh.html", null ],
      [ "GLTFNode", "d9/dec/structworld_1_1_g_l_t_f_node.html", null ],
      [ "GLTFPrimitive", "d7/d4c/structworld_1_1_g_l_t_f_primitive.html", null ],
      [ "GLTFReference", "d1/d07/structworld_1_1_g_l_t_f_reference.html", null ],
      [ "GLTFResource", "de/d7e/classworld_1_1_g_l_t_f_resource.html", null ],
      [ "GLTFScene", "d8/da0/structworld_1_1_g_l_t_f_scene.html", null ],
      [ "GLTFSceneAssets", "d3/d2b/structworld_1_1_g_l_t_f_scene_assets.html", null ],
      [ "GLTFSceneSystem", "df/de2/classworld_1_1_g_l_t_f_scene_system.html", null ],
      [ "ISceneModule", "d5/d00/structworld_1_1_i_scene_module.html", "d5/d00/structworld_1_1_i_scene_module" ],
      [ "LightComponent", "d4/dee/structworld_1_1_light_component.html", null ],
      [ "MagicComponent", "d6/d54/structworld_1_1_magic_component.html", null ],
      [ "NamebleComponent", "da/d6f/structworld_1_1_nameble_component.html", null ],
      [ "PGInstance", "dc/d05/structworld_1_1_p_g_instance.html", null ],
      [ "PGMaterial", "d4/d85/structworld_1_1_p_g_material.html", null ],
      [ "PGMesh", "d3/d2c/structworld_1_1_p_g_mesh.html", null ],
      [ "PGNode", "d8/d0e/structworld_1_1_p_g_node.html", null ],
      [ "PGScene", "d3/d7f/structworld_1_1_p_g_scene.html", null ],
      [ "PGSceneAssets", "db/d4b/structworld_1_1_p_g_scene_assets.html", null ],
      [ "PGSceneSystem", "df/dc8/classworld_1_1_p_g_scene_system.html", null ],
      [ "PhysicsSystem", "d3/ddb/classworld_1_1_physics_system.html", "d3/ddb/classworld_1_1_physics_system" ],
      [ "PhysicsSystemImpl", "d5/d92/classworld_1_1_physics_system_impl.html", null ],
      [ "RenderableComponent", "de/d6d/structworld_1_1_renderable_component.html", null ],
      [ "RenderableSystem", "dd/d4b/classworld_1_1_renderable_system.html", "dd/d4b/classworld_1_1_renderable_system" ],
      [ "RigidbodyComponent", "d0/dcc/structworld_1_1_rigidbody_component.html", null ],
      [ "Scene", "da/d31/classworld_1_1_scene.html", "da/d31/classworld_1_1_scene" ],
      [ "SceneContext", "d3/d3c/classworld_1_1_scene_context.html", null ],
      [ "SceneFlags", "d8/d14/structworld_1_1_scene_flags.html", "d8/d14/structworld_1_1_scene_flags" ],
      [ "SceneSystem", "d5/d98/classworld_1_1_scene_system.html", null ],
      [ "SceneUpdateReg", "db/dbe/classworld_1_1_scene_update_reg.html", null ],
      [ "SelectableComponent", "df/dfc/structworld_1_1_selectable_component.html", null ],
      [ "SpinableComponent", "d8/dcd/structworld_1_1_spinable_component.html", null ],
      [ "TransformComponent", "d7/ddb/structworld_1_1_transform_component.html", "d7/ddb/structworld_1_1_transform_component" ]
    ] ],
    [ "CommandAllocatorPool", "d7/d3b/class_command_allocator_pool.html", null ],
    [ "EditorClient", "d0/d42/class_editor_client.html", null ],
    [ "EditorCMD", "d6/d62/class_editor_c_m_d.html", null ],
    [ "FBitsetBit", "df/d99/class_f_bitset_bit.html", "df/d99/class_f_bitset_bit" ],
    [ "FBitsetIterator", "d3/d5b/class_f_bitset_iterator.html", null ],
    [ "FName", "d5/dd5/class_f_name.html", null ],
    [ "FRenderCamera", "dd/d59/class_f_render_camera.html", null ],
    [ "FSlotArrayIteratorEnd", "d1/d73/struct_f_slot_array_iterator_end.html", null ],
    [ "FUTF8Iterator", "d6/dcc/class_f_u_t_f8_iterator.html", "d6/dcc/class_f_u_t_f8_iterator" ],
    [ "Game", "dd/d1f/class_game.html", null ],
    [ "HQCollectParams", "d6/dae/struct_h_q_collect_params.html", null ],
    [ "HQCursor", "db/d7f/struct_h_q_cursor.html", null ],
    [ "HQCXString", "d0/d37/struct_h_q_c_x_string.html", null ],
    [ "HQHeader", "dd/dca/struct_h_q_header.html", null ],
    [ "HQMacro", "d0/d64/struct_h_q_macro.html", null ],
    [ "HQTimer", "d8/d84/class_h_q_timer.html", null ],
    [ "ImCubicBezierFixedStepSample", "d2/d47/struct_im_cubic_bezier_fixed_step_sample.html", null ],
    [ "ImCubicBezierIntersectResult", "dc/d07/struct_im_cubic_bezier_intersect_result.html", null ],
    [ "ImCubicBezierPointsT", "d1/da4/struct_im_cubic_bezier_points_t.html", null ],
    [ "ImCubicBezierSplitResultT", "d4/da9/struct_im_cubic_bezier_split_result_t.html", null ],
    [ "ImCubicBezierSubdivideSample", "dc/d55/struct_im_cubic_bezier_subdivide_sample.html", null ],
    [ "ImLine", "d4/d77/struct_im_line.html", null ],
    [ "ImProjectResult", "d1/d36/struct_im_project_result.html", null ],
    [ "Path", "de/d1f/class_path.html", "de/d1f/class_path" ],
    [ "Scheduler", "d9/dc4/struct_scheduler.html", null ],
    [ "Task", "d3/d72/struct_task.html", "d3/d72/struct_task" ],
    [ "TBitset", "d7/dde/class_t_bitset.html", "d7/dde/class_t_bitset" ],
    [ "TDynBitset", "d9/d33/class_t_dyn_bitset.html", "d9/d33/class_t_dyn_bitset" ],
    [ "TFlatMap", "df/da2/class_t_flat_map.html", "df/da2/class_t_flat_map" ],
    [ "TFlatMapIterator", "dc/dfe/class_t_flat_map_iterator.html", "dc/dfe/class_t_flat_map_iterator" ],
    [ "TFlatSet", "d8/da1/class_t_flat_set.html", "d8/da1/class_t_flat_set" ],
    [ "TFlatSetIterator", "dd/d29/class_t_flat_set_iterator.html", "dd/d29/class_t_flat_set_iterator" ],
    [ "TModuleRegistry", "d6/d27/class_t_module_registry.html", "d6/d27/class_t_module_registry" ],
    [ "TPImpl", "d9/d4a/class_t_p_impl.html", null ],
    [ "TSlotArray", "d9/dca/class_t_slot_array.html", "d9/dca/class_t_slot_array" ],
    [ "TSlotArrayIterator", "d2/dee/class_t_slot_array_iterator.html", null ],
    [ "TUCallbackData", "d2/dd5/struct_t_u_callback_data.html", null ],
    [ "utf8proc_property_struct", "d9/dfe/structutf8proc__property__struct.html", "d9/dfe/structutf8proc__property__struct" ]
];